import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { DM_Serif_Display, DM_Serif_Text } from "next/font/google";
import { Space_Mono } from "next/font/google";
import { Quantico } from "next/font/google";
import { Turret_Road } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const DMSerifDisplay = DM_Serif_Display({
  weight: "400",
  variable: "--font-dm-serif-display",
  subsets: ["latin"],
});

const DMSerifText = DM_Serif_Text({
  weight: "400",
  variable: "--font-dm-serif-text",
  subsets: ["latin"],
});

const SpaceMono = Space_Mono({
  weight: "400",
  variable: "--font-space-mono",
  subsets: ["latin"],
});

const QuantFont = Quantico({
  weight: "400",
  variable: "--font-quantico",
  subsets: ["latin"],
});

const TurretRoad = Turret_Road({
  weight: "400",
  variable: "--font-turret-road",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${DMSerifDisplay.variable} ${DMSerifText.variable} ${SpaceMono.variable} ${QuantFont.variable} ${TurretRoad.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
